#!/bin/bash

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

MODULES=(
	"${SCRIPT_DIR}/prngine"
)

CLASSPATH="."
for module in ${MODULES[@]}
do
	CLASSPATH="${CLASSPATH}:${module}/build/classes/java/main"
	CLASSPATH="${CLASSPATH}:${module}/build/resources/java/main"
	CLASSPATH="${CLASSPATH}:${module}/build/classes/java/test"
	CLASSPATH="${CLASSPATH}:${module}/build/resources/java/test"
done

CMD="java -cp ${CLASSPATH} $1"
$CMD "${@:2}"
