/*
 * PRNGine - Java PRNG Library (@__identifier__@).
 * Copyright (c) @__year__@ Franz Wilhelmstötter
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author:
 *    Franz Wilhelmstötter (franz.wilhelmstoetter@gmail.com)
 */
package io.jenetics.prngine;

import java.util.Objects;
import java.util.function.IntSupplier;
import java.util.random.RandomGenerator;

/**
 * Base class for random generators which create 32 bit random values natively.
 * Subtypes of this class must only implement the {@link #nextInt()} method.
 * <pre>{@code
 * final class MyRandom extends Random32 {
 *     public int nextInt() {
 *         return ...;
 *     }
 * }
 * }</pre>
 *
 * A quicker way for creating a {@code Random32} instance is using the static
 * factory method {@link #of(IntSupplier)}.
 * <pre>{@code
 * final Random jrand = new Random();
 * final Random32 random = Random32.of(jrand::nextInt);
 * }</pre>
 *
 * @author <a href="mailto:franz.wilhelmstoetter@gmail.com">Franz Wilhelmstötter</a>
 * @since 1.0
 * @version !__version__!
 */
public abstract class Random32 implements RandomGenerator {

	/**
	 * Force to explicitly override the Random.nexInt() method. All other
	 * methods of this class are implemented by calling this method.
	 */
	@Override
	public abstract int nextInt();

	@Override
	public long nextLong() {
		return ((long)nextInt() << 32) + nextInt();
	}

	/**
	 * Create a new {@code Random64} instance, where the random numbers are
	 * generated by the given long {@code supplier}.
	 *
	 * @param supplier the random number supplier
	 * @return a new {@code Random64} instance
	 * @throws java.lang.NullPointerException if the given {@code supplier} is
	 *         {@code null}.
	 */
	public static Random32 of(final IntSupplier supplier) {
		Objects.requireNonNull(supplier);

		return new Random32() {
			@Override
			public int nextInt() {
				return supplier.getAsInt();
			}
		};
	}

}






